# -- rweb_message.tcl
#
# RWMessage is a class for message pages generated by
# error conditions in rivetweb and other application 
# level collaborating classes
#

package require Itcl
package require rwpage

namespace eval ::rwpage {

    ::itcl::class RWBasicPage {
        inherit RWPage

        private variable pagetext
        public  variable rootelement

        constructor {pagekey {message_text ""} {rootel "p"}} {RWPage::constructor $pagekey} {
            set pagetext [dict create $::rivetweb::default_lang $message_text]
            set rootelement $rootel
        }

        public method pagetext_append {language args} {
            dict append pagetext $language "[join $args "\n"]\n"
        }

        public method pagetext {language {page_text ""} {page_title ""}} {

            if {$page_text != ""} {
                $this pagetext_append $language $page_text
            }

            if {$page_title != ""} {
                $this set_title $language $page_title
            }

            if {[dict exists $pagetext $language]} {
                return [dict get $pagetext $language]
            } else {
                return [dict get $pagetext $::rivetweb::default_lang]
            }

        }

        public method print_content {language} {
            puts -nonewline [::rivet::xml [$this pagetext $language] $rootelement]
        }

    }

}
package provide rwbasicpage 0.1

