# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

set rivetweb_dir [file dirname [info script]]
#set msg "RW scripts base directory: $rivetweb_dir"
#if {[catch {::rivet::apache_log_error notice $msg} e]} { puts $msg }

package ifneeded XMLBase 2.1 [list source [file join $rivetweb_dir tcl datasource xmlbase.tcl]]
package ifneeded Scripted 2.0 [list source [file join $rivetweb_dir tcl datasource rwscripted.tcl]]
package ifneeded htmlizer 1.0 [list source [file join $rivetweb_dir tcl htmlizer.tcl]]
package ifneeded rivetweb 2.0 [list source [file join $rivetweb_dir tcl rivetweb.tcl]]
package ifneeded rwconf 2.1 [list source [file join $rivetweb_dir tcl rivetweb_ns.tcl]]
package ifneeded rwlink 2.0 [list source [file join $rivetweb_dir tcl rweb_link.tcl]]
package ifneeded rwlogger 1.0 [list source [file join $rivetweb_dir tcl rwlogger.tcl]]
package ifneeded rwmenu 1.0 [list source [file join $rivetweb_dir tcl rweb_menumodel.tcl]]
package ifneeded rwsitemap 1.0 [list source [file join $rivetweb_dir tcl sitemap.tcl]]
package ifneeded rwterm 0.1 [list source [file join $rivetweb_dir tcl terminal.tcl]]
package ifneeded rwpage 2.0 [list source [file join $rivetweb_dir tcl rweb_page.tcl]]
package ifneeded rwstatic 0.1 [list source [file join $rivetweb_dir tcl rweb_static.tcl]]
package ifneeded rwscripted 0.1 [list source [file join $rivetweb_dir tcl rweb_scripted.tcl]]
package ifneeded ScriptBase 0.1 [list source [file join $rivetweb_dir tcl rweb_scriptbase.tcl]]
package ifneeded RWDummy 1.1 [list source [file join $rivetweb_dir tcl datasource dummy.tcl]]
package ifneeded rwbinary 1.0 [list source [file join $rivetweb_dir tcl rweb_binary.tcl]]
package ifneeded Datasource 1.0 [list source [file join $rivetweb_dir tcl datasource datasource.tcl]]
package ifneeded MessagePrinter 0.1 [list source [file join $rivetweb_dir tcl message_printer_01.tcl]]
package ifneeded MessagePrinter 1.1 [list source [file join $rivetweb_dir tcl message_printer.tcl]]
package ifneeded rwbasicpage 0.1 [list source [file join $rivetweb_dir tcl rweb_basicpage.tcl]]
package ifneeded rwutils 1.0 [list source [file join $rivetweb_dir tcl utils.tcl]]
package ifneeded downloadbin 1.0 [list source [file join $rivetweb_dir tcl downloadbin.tcl]]
package ifneeded rwcontent 1.0 [list source [file join $rivetweb_dir tcl rweb_content.tcl]]
package ifneeded urlcomposer 1.0 [list source [file join $rivetweb_dir tcl urlcomposer.tcl]]
package ifneeded UrlHandler 1.0 [list source [file join $rivetweb_dir tcl urlhandler.tcl]]
package ifneeded RWTemplate 1.0 [list source [file join $rivetweb_dir tcl rweb_template.tcl]]
package ifneeded rwpagebroker 1.0 [list source [file join $rivetweb_dir tcl pagebroker.tcl]]
package ifneeded rwpagecache 1.0 [list source [file join $rivetweb_dir tcl pagecache.tcl]]
package ifneeded rwresource 1.0 [list source [file join $rivetweb_dir tcl resource.tcl]]
package ifneeded rwwebservice 1.0 [list source [file join $rivetweb_dir tcl rweb_webservice.tcl]]
