# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded XMLData 0.1 [list source [file join $dir tcl/datasource/xmldata.tcl]]
package ifneeded XMLMenu 1.0 [list source [file join $dir tcl/datasource/xmlmenu.tcl]]
package ifneeded XMLBase 1.0 [list source [file join $dir tcl/datasource/xmlchunk.tcl]]
package ifneeded htmlizer 1.0 [list source [file join $dir tcl/htmlizer.tcl]]
package ifneeded rivetweb 2.0 [list source [file join $dir tcl/rivetweb.tcl]]
package ifneeded rwconf 2.0 [list source [file join $dir tcl/rivetweb_ns.tcl]]
package ifneeded rwebdb 0.1 [list source [file join $dir tcl/rweb_coredb.tcl]]
package ifneeded rwlink 1.0 [list source [file join $dir tcl/rweb_link.tcl]]
package ifneeded rwlogger 1.0 [list source [file join $dir tcl/rwlogger.tcl]]
package ifneeded rwmenu 1.0 [list source [file join $dir tcl/rweb_menumodel.tcl]]
package ifneeded rwpmodel 0.1 [list source [file join $dir tcl/rweb_pmodel.tcl]]
package ifneeded rwsitemap 1.0 [list source [file join $dir tcl/sitemap.tcl]]
package ifneeded rwterm 0.1 [list source [file join $dir tcl/terminal.tcl]]
package ifneeded rwpage 0.1 [list source [file join $dir tcl/rweb_page.tcl]]
package ifneeded rwstatic 0.1 [list source [file join $dir tcl/rweb_static.tcl]]

